### ISSUE TITLE
Linux / Server / Docker : closes any TCP socket connection immediately

### ISSUE THREAD

**Issue by RomchikL** [JerryI/wolfram-js-frontend#356]
My docker compose config:
```
services:
  wolfram-js-frontend:
    container_name: wljs
    image: "ghcr.io/jerryi/wolfram-js-frontend:main"
#    expose:
#      - "3000"
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    volumes:
      - /etc/mydocker/configs/wolfram/Documents:/workspace
      - /etc/mydocker/configs/wolfram/WolframLicensing:/Licensing
    restart: unless-stopped
    networks:
      - webhosts
    environment:
#      - WOLFRAMID_USERNAME=REDACTED
#      - WOLFRAMID_PASSWORD=REDACTED
      - PUID=1007
      - PGID=1008     
 
 
networks:
  webhosts:
    external: true 
```

Some time after deployment, I see
"Open http://0.0.0.0:4000 in your browser"
In the browser, I get ERR_EMPTY_RESPONSE
And the log has the following:
```
>> InputNamePacket[In[3]:= ]
>> InputNamePacket[In[4]:= ]
>> InputNamePacket[In[5]:= ]
>> InputNamePacket[In[6]:= ]
>> InputNamePacket[In[7]:= ]
>> InputNamePacket[In[8]:= ]
>> InputNamePacket[In[9]:= ]
>> InputNamePacket[In[10]:= ]
>> InputNamePacket[In[11]:= ]
>> InputNamePacket[In[12]:= ]

Open http://0.0.0.0:4000 in your browser
Open http://0.0.0.0:4000 in your browser
>> CSocketObject[10] was Closed
>> CSocketObject[11] was Closed
>> CSocketObject[12] was Closed
>> CSocketObject[13] was Closed
>> CSocketObject[14] was Closed
>> CSocketObject[16] was Closed
>> CSocketObject[17] was Closed
```

The full log:
[wljs_logs.txt](https://github.com/user-attachments/files/19071633/wljs_logs.txt)

**Comment by JerryI** [comment]
Thanks for the full log. Unfortunately, I don't have linux machine nearby. 

I would suggest to install inside the container two things

avachi-daemon
libuv

and try again.

**Comment by JerryI** [comment]
Confirmed on a local Debian x86 with v2.7.0 docker image. This is a bug

**Comment by JerryI** [comment]
Probably all server versions are broken on Linux

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by JerryI** [comment]
Fixed!

See updated instructions [here](https://github.com/JerryI/wolfram-js-frontend/blob/main/container/README.md)

Please reopen if you experience any issues

**Comment by RomchikL** [comment]
Now the container works, but I cannot open any notebooks.
In the log:
```
## Loading by path : 
ping
Default router
>> CSocketObject[85] was Closed
# Loading by path : 
/workspace
>> SHORT!
Default router
>> CSocketObject[86] was Closed
## Loading by path : 
favicon.ico
Default router
>> CSocketObject[87] was Closed
## Loading by path : 
ping
Default router
>> CSocketObject[88] was Closed
# Loading by path : 
/workspace
>> SHORT!
Default router
>> CSocketObject[89] was Closed
## Loading by path : 
favicon.ico
Default router
>> CSocketObject[90] was Closed
```

P.S. I don't have the permissions to reopen the issue, but of course that's a different one.

**Comment by JerryI** [comment]
Hm.. Please try to prune docker images to make sure that no old files left.

**Comment by JerryI** [comment]
PS: Did it load any page?

**Comment by RomchikL** [comment]
> Hm.. Please try to prune docker images to make sure that no old files left.
I've done a clean deployment (with new Wolfram registering)


> PS: Did it load any page?
Yes, it loads the main page, the settings and it seems that it's all (even the buttons don't click)

**Comment by RomchikL** [comment]
Hmm...
A compose config is the similar way to deploy with more control, nothing more.

In the current compose I used "latest" tag. Maybe this is the problem.
Also, I tried to use a reverse proxy. I will try to comment this part and use only IP with ports.

**Comment by RomchikL** [comment]
The current situation.

```
docker rm wljs
docker system prune -a
docker run -it -v /etc/mydocker/configs/wolfram/Documents:/workspace -e PUID=$(id -u) -e PGID=$(id -g) -p 8081:4000 -p 4001:4001 -p 4002:4002 -p 4003:4003 -v /etc/mydocker/configs/wolfram/WolframLicensing:/home/wljs/.WolframEngine/Licensing --name wljs ghcr.io/jerryi/wolfram-js-frontend:main
```
And I also has such page on http://IP:8081/ (Note that the external ports 4000-4003 are closed by external fw, so I use the map 8081->4000):
I also found that our pages differ in "Kernels". It seems that I don't have an active kernel and the "plus" button  is not pressed.
 
<img width="1906" alt="Image" src="https://github.com/user-attachments/assets/9449a1ff-4f44-4c93-9663-0b09152d81c7" />


But I can't click on any button except "Settings", full log:

[Status Downloaded newer image for g.txt](https://github.com/user-attachments/files/19124285/Status.Downloaded.newer.image.for.g.txt)

**Comment by JerryI** [comment]
Ah. Now I see the problem. The original container initializes WebSockets on 4001-*, and generates JS script to connect using this ports. Since you remap externally, script does not know about it.

I think we can fix the image by providing ports as env parameters.

**Comment by RomchikL** [comment]
@JerryI I didn't think the script was using an external port of the container. I think that it is a deal inside the container, so my map is not so important. Well, I was wrong.

Several questions:
1. Can I return the volume with the licence (e.g. /etc/mydocker/configs/wolfram/WolframLicensing:/home/wljs/.WolframEngine/Licensing)
2. Is it possible to mount a volume with all files that are downloaded from the repository during installation

These actions will help to persist necessary files when I update the compose config.
Otherwise, the container downloads new files each time and requires a new license.

**Comment by JerryI** [comment]
> I didn't think the script was using an external port of the container. I think that it is a deal inside the container, so my map is not so important.

I meant the starting script inside the image

```
...
nginx
su - wljs -c "wolframscript -activate"
su - wljs -c "wolframscript -f /wljs/Scripts/start.wls host 0.0.0.0 http 4000 ws 4001 ws2 4002 docs 4003"
```

remapping of http is fine, but then JS on the page will try to knock the original 4001, 4002 ports, which are remapped and therefore you have no UI response 


> Several questions:

> Can I return the volume with the licence (e.g. /etc/mydocker/configs/wolfram/WolframLicensing:/home/wljs/.WolframEngine/Licensing)
> Is it possible to mount a volume with all files that are downloaded from the repository during installation

Good idea!

**Comment by RomchikL** [comment]
> remapping of http is fine, but then JS on the page will try to knock the original 4001, 4002 ports, which are remapped and therefore you have no UI response

My global plan is to use the container behind the nginx with basic auth (the linux machine is located on a public place with an external IP address). For security reasons, opening ports is an undesirable action. So, I was planning to use the project with the following config:

```
services:
  wolfram-js-frontend:
    container_name: wljs
    image: "ghcr.io/jerryi/wolfram-js-frontend:main"
    expose:
      - "3000"
#    ports:
#      - "8081:4000"
#      - "4001:4001"
#      - "4002:4002"
#      - "4003:4003"
    volumes:
      - /etc/mydocker/configs/wolfram/Documents:/workspace
      - /etc/mydocker/configs/wolfram/WolframLicensing:/home/wljs/.WolframEngine/Licensing
      - "some another path":"a folder with downloaded files"
    restart: unless-stopped
    networks:
      - webhosts
    environment:
#      - WOLFRAMID_USERNAME=REDACTED
#      - WOLFRAMID_PASSWORD=REDACTED
      - PUID=1007
      - PGID=1008     
      - VIRTUAL_HOST=xxx.yyy.zzz
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=xxx.yyy.zzz
```

And use it on xxx.yyy.zzz without any opened ports.
